"use client"
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js/react'

import _supplier_table from './supplier-table.bones.json'

registerBones({
  "supplier-table": _supplier_table,
})
